# Generated by Django 3.0.4 on 2020-04-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site_Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('screenshot', models.ImageField(default='no-image-big.jpg', upload_to='site-previews/')),
                ('descrizione', models.TextField()),
                ('url', models.URLField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
