# Generated by Django 3.0.4 on 2020-04-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200426_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='anteprima_immagine',
            field=models.ImageField(default='no-image-small.png', upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='immagine',
            field=models.ImageField(default='no-image-big.jpg', upload_to='images/%Y/%m/%d/'),
        ),
    ]
