# Generated by Django 3.0.6 on 2020-05-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200428_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='anteprima_immagine',
            field=models.ImageField(blank=True, default='media/no-image-small.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='immagine',
            field=models.ImageField(blank=True, default='media/no-image-big.jpg', upload_to=''),
        ),
    ]
